### ISSUE TITLE
Screenshots in Readme.md File

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [Vyvy-vi/dev-quotes-api-sync#21]
### Improve readme and documentation using Screenshots

- (Love the Changelogs.)

**Comment by Vyvy-vi** [comment]
Thanks for opening this issue!
A screenshot of the index page or from a request might be nice :)

**Comment by Vyvy-vi** [comment]
This issue was closed by 132421916ec3fd00bc03c7a51f8eb3e0d0788bd1

**Comment by Prathamesh-Shanbhag** [comment]
Glad to see that it was added awesome work!
