### ISSUE TITLE
labels GitHub action 

### ISSUE THREAD

**Issue by eddiejaoude** [Vyvy-vi/dev-quotes-api-sync#23]
Using the labels Action will standardise the labels

**Comment by Vyvy-vi** [comment]
Thanks for opening this issue! The labels action would be great

**Comment by Prathamesh-Shanbhag** [comment]
I wanted to know if you manually added the labels?
& after you close the request will it get added automatically?

**Comment by Vyvy-vi** [comment]
No, the github action is mainly a way to refresh your default labels and replace them with conventional lables

**Comment by Prathamesh-Shanbhag** [comment]
Awesome thanks for clearing that up!
